modLoader = "javafml"
loaderVersion = "[40,)"
license = "MIT"
[[mods]]
modId = "crittersandcompanions"
version = "${file.jarVersion}"
displayName = "Critters and Companions"
logoFile = "logo.png"
authors = "Joosh, EterDelta"
description = '''
Critters and Companions is a vanilla-style creature mod which fills the overworld with new animals.
'''

[[dependencies.crittersandcompanions]]
modId = "geckolib"
mandatory = true
versionRange = "[4.4.2,)"
ordering = "AFTER"
side = "BOTH"
[[dependencies.crittersandcompanions]]
modId = "forge"
mandatory = true
versionRange = "[47.1.3,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.crittersandcompanions]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"
